# ----------------------------------------------------------------------------
#
# Package             : woodstox-core
# Source Repo         : https://github.com/FasterXML/woodstox.git
# Travis Job Link     : https://travis-ci.com/github/santosh653/woodstox
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
    - amd64
    - ppc64le
language: java

jdk:
  - openjdk8
  - openjdk11
#Excluding openjdk8 & running the code on only openjdk11 
jobs:
 exclude:
  - jdk: openjdk8
    arch: ppc64le

# TODO: travis snapshots?
after_success:
  - "mvn -B cobertura:cobertura coveralls:report"

branches:
  only:
    - master
    - "5.3"
